version: '2.4'
services:
    php:
        build:
            context: ./docker/config/php
            args:
                PROJECT_USER_ID: ${PROJECT_USER_ID}
                PROJECT_GROUP_ID: ${PROJECT_GROUP_ID}
        container_name: ${PROJECT_NAME}-php
        hostname: ${PROJECT_NAME}-php
        volumes:
            - ./:/var/www:delegated
            - ./docker/config/php/override-php.ini:/usr/local/etc/php/conf.d/override-php.ini:delegated
            - ./docker/config/php/override-fpm.conf:/usr/local/etc/php-fpm.d/yoverride-fpm.conf:delegated
            - ./docker/data/php/project:/home/project:cached
            - ./docker/var:/var/project:cached
        working_dir: /var/www
        env_file: .env
        restart: unless-stopped
